### ISSUE TITLE
Inconsistency jQuery dependency 

### ISSUE THREAD

**Issue by ganjarsetia** [zuramai/mazer#114]
In README I saw No  jQuery dependency

![image](https://user-images.githubusercontent.com/3258090/182912527-7d94d438-d63e-41b3-bd1e-58556bc10f50.png)

But in your depedencies https://github.com/zuramai/mazer/blob/main/package.json#L57 still using jQuery

Which is right ?

------

Gimana nih mas yang bener yang mana? datatable nya juga masih ada jQuery nya :laughing: 

Templatenya bagus, baiknya bener2 ga pake jQuery sama sekali

**Comment by zuramai** [comment]
No jQuery dependency is absolutely right.
We added the jQuery dependency not because Mazer depends on jQuery, but we just provide it in case people want to use it for other libraries with jQuery dependency. 

For example, if you want to use [https://datatables.net](https://datatables.net/), you must add jQuery. It's not the Mazer that depends on jQuery, but if you want to use a library with jQuery dependency, you can directly link the provided `jquery.min.js`.

For some libraries that use jQuery, it's clearly stated in the menu. The rest is not using jQuery.
![image](https://user-images.githubusercontent.com/45036724/182968001-a730921a-fc2b-4f42-ad9f-574324f0d2bc.png)
