### ISSUE TITLE
Multi level menu

### ISSUE THREAD

**Issue by BayuZangetsu** [zuramai/mazer#204]
halo, saya sangat menyukai desain dari template ini project yang sangat bagus.
namun apakah bisa dibuat agar menu menjadi 2 level?
dimana menu memiliki submenu dan submenu tersebut memiliki menu lagi (2nd level menus)
terimakasih

![image](https://user-images.githubusercontent.com/23151434/226509411-83fd5538-c886-4363-bec0-a9d93e32768a.png)

**Comment by zuramai** [comment]
Implemented [319c800](https://github.com/zuramai/mazer/pull/209/commits/319c800767af91ad044065d0ac8052d4858c8ec8).

**Comment by cyphos1973** [comment]
Hi
possible to add the 3d level ?
because I tried and I don't work
thanks you for your help

`<li class="sidebar-item has-sub">
    <a href="#"
       class="sidebar-link">
        <i class="bi bi-collection"></i>
        <span>Multi-level Menu</span>
    </a>
    <ul class="submenu">
        <li class="submenu-item has-sub">
            <a href="#"
               class="submenu-link">Level 1.1</a>

            <ul class="submenu submenu-level-2">
                <li class="submenu-item has-sub">
                    <a href="#"
                       class="submenu-link">Level 2.1</a>

                    <ul class="submenu submenu-level-2">
                        <li class="submenu-item">
                            <a href="#"
                               class="submenu-link">Level 3.1</a>
                        </li>

                        <li class="submenu-item">
                            <a href="#"
                               class="submenu-link">Level 3.2</a>
                        </li>
                    </ul>
                </li>

                <li class="submenu-item">
                    <a href="#"
                       class="submenu-link">Level 2.2</a>
                </li>
            </ul>
        </li>

        <li class="submenu-item has-sub">
            <a href="#"
               class="submenu-link">Level 1.2</a>
            <ul class="submenu submenu-level-2">
                <li class="submenu-item">
                    <a href="#"
                       class="submenu-link">Level 2.1</a>
                </li>
            </ul>
        </li>
    </ul>
</li>`

**Comment by jvl1v5** [comment]
Abwesenheitsnotiz:


Vom 22.06.2023  bis einschließlich 11.07.2023  bleibt unser Büro geschlossen. E-Mails werden entsprechend der Dringlichkeit verzögert bearbeitet.


In Notfällen benutzen Sie bitte das telefonische Notfallsystem unter 02206-95100-0.


Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während wir abwesend sind.

Beste Grüße
1 Qubit - J.Suing


-------------------------------------------------------------------------
1 Qubit - J.Suing
Laurentiusstr. 41 - 51789 Lindlar
fon: 02206-95100-0 - fax: 02206-95100-29

Portfolio
STARFACE Telefonanlagen
Software-Entwicklung
Firewall, Security, UTM, VPN
Mailserver / Unified Messaging
CRM / ERP


Partner
STARFACE Advanced Partner
STARFACE Module Creator
Securepoint Professional Partner
Tobit Software Authorized Partner
work4all! Solution Partner
Kerio Partner

Blog, Forum, Module und mehr...
www.1qubit.de
-------------------------------------------------------------------------




  
Hi
possible to add the 3d level ?
because I tried and I don't work
thanks you for your help

`<li class="sidebar-item has-sub">
    <a href="#"
       class="sidebar-link">
        <i class="bi bi-collection"></i>
        <span>Multi-level Menu</span>
    </a>
    <ul class="submenu">
        <li class="submenu-item has-sub">
            <a href="#"
               class="submenu-link">Level 1.1</a>

            <ul class="submenu submenu-level-2">
                <li class="submenu-item has-sub">
                    <a href="#"
                       class="submenu-link">Level 2.1</a>

                    <ul class="submenu submenu-level-2">
                        <li class="submenu-item">
                            <a href="#"
                               class="submenu-link">Level 3.1</a>
                        </li>

                        <li class="submenu-item">
                            <a href="#"
                               class="submenu-link">Level 3.2</a>
                        </li>
                    </ul>
                </li>

                <li class="submenu-item">
                    <a href="#"
                       class="submenu-link">Level 2.2</a>
                </li>
            </ul>
        </li>

        <li class="submenu-item has-sub">
            <a href="#"
               class="submenu-link">Level 1.2</a>
            <ul class="submenu submenu-level-2">
                <li class="submenu-item">
                    <a href="#"
                       class="submenu-link">Level 2.1</a>
                </li>
            </ul>
        </li>
    </ul>
</li>`
