### ISSUE TITLE
Clicking a link in a multi-level menu will collapse it

### ISSUE THREAD

**Issue by 1041241122** [zuramai/mazer#283]
Can fix the problem of clicking links in multi-level menu not to collapse?
![724750839 698024](https://github.com/zuramai/mazer/assets/54347654/46c6ac74-54f2-452f-bd49-aee7b53e5979)

**Comment by zuramai** [comment]
It is because the link you click has `href='#'`, it will do the default actions if the browser is not redirecting you to another link

**Comment by jvl1v5** [comment]
Abwesenheitsnotiz: 
Vom 22.12.2023  bis einschl. 03.01.2024  befinde ich mich im Urlaub.

E-Mails werden nur verzögert gelesen.

In sehr dringenden Fällen und in Notfällen sprechen Sie bitte eine Nachricht auf den Notruf-Anrufbeantworter unter 02206-95100-0. Geben Sie dabei Name, Rufnummer und die Art des Notfalls an. Wenn es sich um einen sehr dringenden Fall oder einen Notfall handelt, werde ich mich zeitnah bei Ihnen melden. Andernfalls stehe ich nach meinem Urlaub wieder wie gewohnt für Sie zur Verfügung.
 
Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während ich abwesend bin.
 
 
Beste Grüße
Jens Suing
 
-------------------------------------------------------------------------
Visitenkarte (vcf)
-------------------------------------------------------------------------
DIE Spezialisten - J.Suing
Laurentiusstr. 41 - 51789 Lindlar
fon: 02206-95100-0 - fax: 02206-95100-29
------------------------------------------------------------------------- 
Tobit Software Authorized Partner *****
Starface Advanced Partner
work4all! Solution Partner
bintec elmeg Certified Partner
Kerio Partner 

 
News, Forum, FAQ und mehr...
www.schneller-und-besser.de
-------------------------------------------------------------------------

 


 
It is because the link you click has `href='#'`, it will do the default actions if the browser is not redirecting you to another link

**Comment by jvl1v5** [comment]
Abwesenheitsnotiz: 
Vom 22.12.2023  bis einschl. 03.01.2024  befinde ich mich im Urlaub.

E-Mails werden nur verzögert gelesen.

In sehr dringenden Fällen und in Notfällen sprechen Sie bitte eine Nachricht auf den Notruf-Anrufbeantworter unter 02206-95100-0. Geben Sie dabei Name, Rufnummer und die Art des Notfalls an. Wenn es sich um einen sehr dringenden Fall oder einen Notfall handelt, werde ich mich zeitnah bei Ihnen melden. Andernfalls stehe ich nach meinem Urlaub wieder wie gewohnt für Sie zur Verfügung.
 
Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während ich abwesend bin.
 
 
Beste Grüße
Jens Suing
 
-------------------------------------------------------------------------
Visitenkarte (vcf)
-------------------------------------------------------------------------
DIE Spezialisten - J.Suing
Laurentiusstr. 41 - 51789 Lindlar
fon: 02206-95100-0 - fax: 02206-95100-29
------------------------------------------------------------------------- 
Tobit Software Authorized Partner *****
Starface Advanced Partner
work4all! Solution Partner
bintec elmeg Certified Partner
Kerio Partner 

 
News, Forum, FAQ und mehr...
www.schneller-und-besser.de
-------------------------------------------------------------------------

 


 
Closed #283 as completed.

-- 
Reply to this email directly or view it on GitHub:
https://github.com/zuramai/mazer/issues/283#event-11334917181
