### ISSUE TITLE
Horizontal Layout does not fit the screen

### ISSUE THREAD

**Issue by lilouch** [zuramai/mazer#29]
Hi,

The horizontal Layout does not fit the screen is the latter is wider or if I dezoom. It stays fixed.

thank you

**Comment by zuramai** [comment]
Do yo mean the screen stay at the center even you zoom out? 

Indeed it is, because if the screen does not use `.container` class, it will stretch awfully and it doesn't seem fit to the navbar-on-top layout.

If you want the screen to stretch on zoom out, remove the `.container` class from the layout and it will solve the problem.
